[package]
name = "lasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
crossterm = "0.27.0"
nom = "7.1.3"
ratatui = "0.23.0"
